import { StyleSheet } from 'react-native';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    paddingHorizontal: 0,
    
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 45,
    marginBottom: 8,
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
  },
  backText: {
    fontSize: 20,
    color: '#6c63ff',
    fontWeight: 'bold',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#3d3d3d',
  },
  profileCard: {
    backgroundColor: '#fff',
    marginHorizontal: 24,
    borderRadius: 24,
    alignItems: 'center',
    paddingVertical: 24,
    marginBottom: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  avatarContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#edeaff',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    elevation: 2,
  },
  avatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
  },
  name: {
    fontSize: 20,
    fontWeight: '700',
    color: '#3d3d3d',
    marginBottom: 2,
  },
  specialty: {
    fontSize: 15,
    color: '#6c63ff',
    marginBottom: 4,
  },
  patientInfo: {
    fontSize: 13,
    color: '#888',
    marginBottom: 2,
  },
  review: {
    fontSize: 13,
    color: '#888',
    marginBottom: 0,
  },
  statsGrid: {
    marginHorizontal: 24,
    marginBottom: 24,
    gap: 16,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 16,
  },
  statBox: {
    flex: 1,
    minWidth: 0,
    backgroundColor: '#f6f6fa',
    borderRadius: 16,
    alignItems: 'center',
    paddingVertical: 18,
    marginHorizontal: 0,
    elevation: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  statBoxGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  statIcon: {
    width: 32,
    height: 32,
    marginBottom: 6,
  },
  statValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#3d3d3d',
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
  },
  logoutButton: {
    alignItems: 'center',
    marginTop: 8,
  },
  logoutText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 1,
  },
  actionBoxContainer: {
    flexDirection: 'row',
    backgroundColor: 'white',
    borderRadius: 24,
    padding: 16,
    marginHorizontal: 40,
    marginBottom: 24,
    marginTop: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 10,
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 0,
    marginBottom: 0,
    marginTop: 0,
    paddingBottom: 0,
    height: 80,
  },
  actionItem: {
    alignItems: 'center',
    flex: 1,
  },
  squareButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  roundButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#6c63ff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    zIndex: 2,
  },
  actionIcon: {
    fontSize: 26,
    color: '#6c63ff',
    fontWeight: 'bold',
  },
  actionLabel: {
    fontSize: 12,
    color: '#888',
    marginTop: 6,
    textAlign: 'center',
  },
  'roundButtonText': {
    color: '#fff',
    fontSize: 30,
    fontWeight: 'bold',
  },
  actionIconImg: {
    width: 44,
    height: 44,
    borderRadius: 32,

  },
  actionIconImgCamera: {
    width: 64,
    height: 64,
    borderRadius: 32,
  },
}); 